# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190812_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 12, 12, 55, 3, 290349, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
