# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_image_big'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='segment',
            field=models.IntegerField(null=True),
        ),
    ]
