# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_bid_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle', models.PositiveIntegerField(default=0)),
                ('auction_1', models.PositiveIntegerField(default=0)),
                ('auction_2', models.PositiveIntegerField(default=0)),
                ('auction_3', models.PositiveIntegerField(default=0)),
                ('auction_4', models.PositiveIntegerField(default=0)),
                ('subscriptions', models.PositiveIntegerField(default=0)),
                ('others', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
