# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
