# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20191202_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
